### PR TITLE
Fix for immediately login

### PR DESCRIPTION
**Pull request by pangeran-bottor**
It works now.

Additional comment 
IMHO, we need to make the program become more modular. The original modules are a little complicated (many dependencies, from one module to another).
Plus, please state some clear milestone/functions/features that needed. It'll really helpful to give contributors some directions.

### CODE REVIEW

**Comment by tp9** [comment]
This is starting to get confusing. There are 2 projects in this git and the bugs are not specific to a particular project.

**Comment by MihaiPro** [comment]
we are working now  on bank project, pygame project is inactive.

**Comment by tp9** [comment]
Oh. Why? The pygame project actually looks more interesting and the code is cleaner too. Who started the pygame code?

**Comment by MihaiPro** [comment]
alex started it. it will be more complicated, so we decided to start to something more simple.

**Comment by tp9** [comment]
It's only a block moving on a screen. Are you guys unfamiliar with the Pygame library?

If so, that might be a problem. I was under the impression that everyone would be at least up to the level of the pygame code.

**Comment by tp9** [comment]
Can we take this to chat BTW?

https://gitter.im/tp9/OpenSourceProjects

**Comment by MihaiPro** [comment]
I can't merge this , but your code works , so I give you rights and you can do modifications

**Pull request closed without merging**
